LINK-113 - FT - Estructura de proyecto y home
eventoL/eventol-auth-ui pull request #1
Opened 2016-12-30 15:53 UTC by ChmlGr

2017-01-01 00:36 UTC, reyiyo requested changes

2017-01-01 00:36 UTC, reyiyo commented on app/controllers/user.js
> +                $http
acá tendría que llevar un return

2017-01-01 00:36 UTC, reyiyo commented on app/controllers/user.js
> +            this.createUser = function() {
conviene nombrar todas las funciones así dps si hay un error no dice "anonymous"... this.createUser = function createUser() {}

2017-01-01 00:36 UTC, reyiyo commented on Gruntfile.js
> +            watch  : {
el watch me parece que no existe

2017-01-01 00:36 UTC, reyiyo commented on app/src/user/components/menu/menu.html
> +                    <md-icon md-font-icon ng-class="vm.userStatus.icon" ng-style="{'color': vm.userStatus.color }" class="icon status s16">
este "vm.userStatus..." es algo que yo no encuentro, viene de otro lado, o habría que cambiarlo a $ctrl ?

2017-01-01 00:36 UTC, reyiyo commented on app/src/home/home.html
> +            </naviation>
typo?

2017-01-01 00:36 UTC, reyiyo commented on app/app-dev.js
> +        .module('protractor-example-dev', ['protractor-example', 'ngMockE2E'])
este debería llamarse dogo-dev

2017-01-01 00:36 UTC, reyiyo commented on app/app-dev.js
> +            angular.bootstrap(document, ['protractor-example-dev']);
idem, dogo-dev

2017-01-01 00:36 UTC, reyiyo commented on app/constants/api.js
> +    angular.module('protractor-example')
este debería llamarse dogo

2017-01-01 00:36 UTC, reyiyo commented on app/controllers/user.js
> +    angular.module('protractor-example')
este debería llamarse "dogo"

2017-01-01 00:36 UTC, reyiyo commented on app/controllers/user.js
> +'use strict';
este archivo debería ir dentro de src/user

2017-01-01 00:36 UTC, reyiyo commented on app/appConfig.js
> +        $mdIconProvider.iconSet('avatars', 'assets/angular-material-assets/icons//avatar-icons.svg', 128);
acá te quedó una "//"

2017-01-01 00:36 UTC, reyiyo commented on app/appConfig.js
> +            controllerAs:'cntrl'
como convención usamos sarazaController

2017-01-01 14:01 UTC, ChmlGr commented on app/controllers/user.js
> +                $http
Borrado el archivo que no se usa

2017-01-01 14:01 UTC, ChmlGr commented on app/controllers/user.js
> +            this.createUser = function() {
Borrado el archivo que no se usa

2017-01-01 14:01 UTC, ChmlGr commented on app/controllers/user.js
> +    angular.module('protractor-example')
Borrado el archivo que no se usa

2017-01-01 14:01 UTC, ChmlGr commented on app/controllers/user.js
> +'use strict';
Borrado el archivo que no se usa

2017-01-01 14:04 UTC, ChmlGr commented on app/constants/api.js
> +    angular.module('protractor-example')
Borrado el archivo que no se usa

2017-01-01 14:06 UTC, ChmlGr commented on app/appConfig.js
> +            controllerAs:'cntrl'
> Controllers are plain javascript constructors, so they will be named UpperCamelCase (HomePageCtrl, ShoppingCartCtrl, AdminPanelCtrl, etc.).

2017-01-02 13:50 UTC, reyiyo approved these changes
:D

2017-01-02 13:50 UTC, merged