LINK-109 - Login service
eventoL/eventol-auth-ui pull request #3
Opened 2017-01-04 02:29 UTC by ChmlGr

2017-01-04 10:45 UTC, reyiyo requested changes

2017-01-04 10:45 UTC, reyiyo commented on app/src/login/login.html
> +                <div layout="row" layout-padding layout-wrap layout-fill ng-hide="$ctrl.msg == null">
=== null

2017-01-04 10:45 UTC, reyiyo commented on app/src/login/login.js
> +    .config(function loginConfig() {
si no se hace nada dentro del config, saquemoslo

2017-01-04 10:45 UTC, reyiyo commented on app/src/login/loginController.js
> +        $scope.login = function login() {
como práctica nuestra, no solemos poner las cosas en $scope. Esta function la dejaríamos en el ctrl y la llamaríamos con $ctrl.login() desde el html.

2017-01-04 10:45 UTC, reyiyo commented on app/src/login/loginController.js
> +            var credentials = $scope.$ctrl.form;
siguiendo con lo anterior, acá podrías hacer un "var credentials = {}" y en el form en el html, usarlo como ng-model (ng-model="$ctrl.credentials")

2017-01-04 10:45 UTC, reyiyo commented on app/src/login/loginController.js
> +                    store.set('jwt', token);
No estoy seguro, pero creo que esto lo deberíamos manejar al menos por usuario. Haceme acordar que lo charlamos hoy :)

2017-01-04 10:45 UTC, reyiyo commented on app/src/login/loginController.js
> +                    $scope.$ctrl.msg = errorMsg;
idem $scope

2017-01-04 10:45 UTC, reyiyo commented on app/src/login/loginService.js
> +    .service('loginService', function loginService($http) {
acá el function sería "LoginService"

2017-01-04 10:45 UTC, reyiyo commented on app/src/login/loginService.js
> +        var urlLogin = 'http://localhost:3000/api/login';
Esto deberíamos pasarlo a una constante (o no me acuerdo como lo estábamos haciendo, hay que preguntarle a @AgustinCroce). Igual, para el próximo review, no para este!

2017-01-04 10:45 UTC, reyiyo commented on app/src/register/register.html
> +                    <input name="username" ng-model="vm.form.username" placeholder="Name"
vm -> $ctrl

2017-01-04 10:45 UTC, reyiyo commented on app/src/register/register.html
> +                    <input type="email" name="email" ng-model="vm.form.email" placeholder="Email"
idem vm

2017-01-04 10:45 UTC, reyiyo commented on app/src/register/register.html
> +                           ng-pattern="/^.+@.+\..+$/" required>
No se si es necesario el pattern, ya que me parece que la validación se hace por html5 con el type=email

2017-01-04 10:45 UTC, reyiyo commented on app/src/register/register.html
> +                    <md-checkbox name="terms" ng-model="data.cb1" aria-label="I read and accept" required></md-checkbox>
esto tendría que ir en el mismo ng-model que user y pass

2017-01-04 12:15 UTC, ChmlGr commented on app/src/login/loginService.js
> +        var urlLogin = 'http://localhost:3000/api/login';
I know

2017-01-04 12:16 UTC, ChmlGr commented on app/src/register/register.html
> +                           ng-pattern="/^.+@.+\..+$/" required>
Creo que eso es para el ng-message igual, que salte el 'Invalid email'

2017-01-04 12:16 UTC, ChmlGr commented on app/src/register/register.html
> +                    <md-checkbox name="terms" ng-model="data.cb1" aria-label="I read and accept" required></md-checkbox>
lo de los TOS? Pensaba volarlo

2017-01-04 14:11 UTC, ChmlGr commented on app/src/login/login.html
> +                <div layout="row" layout-padding layout-wrap layout-fill ng-hide="$ctrl.msg == null">
no funciona con ===

2017-01-04 14:50 UTC, ChmlGr commented on app/src/login/loginController.js
> +                    store.set('jwt', token);
Esto esta resuelto entonces?

2017-01-04 14:58 UTC, reyiyo commented on app/src/register/register.html
> +                           ng-pattern="/^.+@.+\..+$/" required>
:+1:

2017-01-04 14:58 UTC, reyiyo commented on app/src/register/register.html
> +                    <md-checkbox name="terms" ng-model="data.cb1" aria-label="I read and accept" required></md-checkbox>
:+1:

2017-01-04 18:31 UTC, reyiyo requested changes

2017-01-04 18:31 UTC, reyiyo commented on app/appConfig.js
> +            controller: 'RegisterController',
Cambiar "register" por "signup" :)

2017-01-04 18:43 UTC, reyiyo approved these changes

2017-01-06 23:59 UTC, reyiyo requested changes

2017-01-06 23:59 UTC, reyiyo commented on app/appConfig.js
> +            controller: 'HomeController',
Deberíamos ser consistentes con usar controllerAs en todos o en ninguno

2017-01-06 23:59 UTC, reyiyo commented on app/src/auth/auth.js
> +'use strict';
auth-service.js (al archivo)

2017-01-06 23:59 UTC, reyiyo commented on app/src/login/login.html
> +                            <span translate="LOGIN.ERRORS.USERNAME_REQUIRED">Username field is required</span>
Username is required

2017-01-06 23:59 UTC, reyiyo commented on app/src/login/login.html
> +                            <span translate="LOGIN.ERRORS.PASSWORD_REQUIRED">Password field is required</span>
Password is required

2017-01-06 23:59 UTC, reyiyo commented on app/src/login/loginController.js
> +'use strict';
Perdón que no lo vi antes... como convención para el nombre de los archivos usamos "login-controller.js" más que nada porque el browser y algunos SO son case insensitive

2017-01-06 23:59 UTC, reyiyo commented on app/src/signup/signup.html
> +                            <span translate="REGISTER.ERRORS.USERNAME_REQUIRED">Username field is required</span>
Username is required

2017-01-06 23:59 UTC, reyiyo commented on app/src/signup/signup.html
> +                            <span translate="REGISTER.ERRORS.EMAIL_REQUIRED">Email field is required</span>
Email is required

2017-01-06 23:59 UTC, reyiyo commented on app/src/signup/signup.html
> +                            <span translate="REGISTER.ERRORS.PASSWORD_REQUIRED">Password field is required</span>
Password is required

2017-01-06 23:59 UTC, reyiyo commented on app/src/signup/signup.html
> +                            <span translate="REGISTER.ERRORS.PASSWORD_CONFIRM_REQUIRED">Password (Confirm) field is required</span>
Password confirmation is required

2017-01-07 01:29 UTC, reyiyo approved these changes

2017-01-07 01:29 UTC, merged